spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

spring:
  profiles: dev	
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?characterEncoding=utf8&serverTimezone=GMT%2B8            # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      validation-query: SELECT 1

eureka:
  client: #客户端注册进eureka服务列表内com.atguigu.springcloud
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: atguigu-microservicecloud-springcloudconfig01
  company.name: www.atguigu.springcloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001

spring:
  profiles: test	
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?characterEncoding=utf8&serverTimezone=GMT%2B8            # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      validation-query: SELECT 1

eureka:
  client: #客户端注册进eureka服务列表内com.atguigu.springcloud
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: atguigu-microservicecloud-springcloudconfig02
  company.name: www.atguigu.springcloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$
